spring:
  application:
    name: urlshorterner
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:postgresql://localhost:5432/shorturldb"
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariPool-1
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true

shorten:
  url:
    domain: localhost:8080
